spring:
  profiles:
    active: dev

  application:
    name: "cross-project"
    version: "0.1"

  datasource:
    url: jdbc:postgresql://localhost:5432/cross_project
    username: postgres
    password: student321
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  web:
    resources:
      static-locations: classpath:/static/,file:./uploads/

server:
  port: 8080
  
jwt:
    secret: 66f65f5f97904ad05148f5a25c3f24adabf0d0f9b7c5ad09344393a55b8deeef
    access:
        duration:
            minutes: 5
            seconds: 300
        cookie-name: access-token
    refresh:
        duration:
            days: 7
            seconds: 604800
        cookie-name: refresh-token
        
logging:
  level:
    root: INFO
    com.example.cross_project: DEBUG 
    org.springframework: WARN         
    org.hibernate: INFO
  file:
    name: logs/cross-project.log      
    max-size: 10MB                     
    max-history: 30                     
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %cyan(%logger{36}) - %level - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %level - %msg%n"

file:
  upload:
    dir: ./uploads
    
telegram:
  bot:
    token: "5406798562:AAGsKqSsApGWe19tu2ZXd6Mt2GJXn9OEJiY"
    chat-id: "692770192"
    
report:
  template-location: classpath:templates/alert_template.xlsx